POST http://localhost:3001/api/v1/users/register
Content-Type: application/json

{
    "username": "bungio20k",
    "password": "toan1402",
    "email": "bungio20k@gmail.com"
}

###
POST http://localhost:3001/api/v1/users/login
Content-Type: application/json

{
    "username": "Bungio20k",
    "password": "toan1402"
}

###
GET http://localhost:3001/api/v1/wallets
Authorization: BEARER eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkJ1bmdpbzIwayIsImlhdCI6MTY1MzExNzI3MCwiZXhwIjoxNjUzMjAzNjcwfQ.HdW5hT_Ag_Ktz8ygeFnoXqBTGmLBcm_wqQeWDY9_jv4
